version: "3"
services:
  web:
    build: .
    container_name: nginxReverseProxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - ./letsencrypt/:/etc/letsencrypt/
